### ISSUE TITLE
Error when exporting from Pocahontas Animated Storybook

### ISSUE THREAD

**Issue by headsetguy37** [npjg/MediaStation#4]
When running MediaStation.exe on the directory (copied to my hard drive), I receive the following warnings and errors:
```
Processing matched file POCA_P6546\BOOT.STM
WARNING:root:Detected unknown section 0x000c
WARNING:root:Detected unknown section 0x0064
WARNING:root:Detected unknown section 0x006b
Processing matched file POCA_P6546\100.CXT
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Scripts\MediaStation.exe\__main__.py", line 7, in <module>
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\MediaStation\Engine.py", line 70, in main
    media_station_engine.process(command_line_arguments.input, file_detection_entries)
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\asset_extraction_framework\Application.py", line 57, in process
    self.process(sub_directory_path, [file_detection_entry])
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\asset_extraction_framework\Application.py", line 66, in process
    processed_file = file_detection_entry.file_processor(path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\MediaStation\Context.py", line 198, in __init__
    Datum(self.stream)
  File "C:\Users\thevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\MediaStation\Primitives\Datum.py", line 85, in __init__
    raise ValueError(f'Unknown datum type: 0x{self.t:04x}')
ValueError: Unknown datum type: 0x6769
```
No files are extracted. No JSON is saved.

OS: Windows 11 Pro 22H2
Python version: 3.12 64-bit
MediaStation version: latest release from PyPI (sorry, don't know which version number that would be)
CPU: AMD Ryzen 7 7700X

If you need any more info about my operating environment, let me know!

**Comment by npjg** [comment]
Do you have the specific version of Pocahontas this failed on? I suspect it's fixed now but want to make sure. See https://github.com/npjg/MediaStation/wiki/All-Known-Media-Station-Titles#contributing for instructions on getting the version from running in an emulator?
