### ISSUE TITLE
Problems with exporting items from Pooh Animated Storybook

### ISSUE THREAD

**Issue by Puterboy1** [npjg/MediaStation#5]
C:\Users\jaker>C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\MediaStation.exe "C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA" "C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\Export"
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\BOOT.STM
---
WARNING:root:Detected unknown section 0x000c
WARNING:root:Detected unknown section 0x0064
WARNING:root:Detected unknown section 0x0066
---
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\100.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\104.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\120.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\126.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\158.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\159.CXT
Processing matched file C:\Users\jaker\Downloads\Disney's Animated Storybook Winnie the Pooh and the Honey Tree\DATA\161.CXT
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\MediaStation.exe\__main__.py", line 7, in <module>
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\MediaStation\Engine.py", line 138, in main
    media_station_engine.process(command_line_arguments.input, file_detection_entries)
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\asset_extraction_framework\Application.py", line 66, in process
    self.process(sub_directory_path, [file_detection_entry])
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\asset_extraction_framework\Application.py", line 75, in process
    processed_file = file_detection_entry.file_processor(path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\MediaStation\Context.py", line 204, in __init__
    chunk = self.read_old_style_header_sections(subfile, chunk)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\MediaStation\Context.py", line 271, in read_old_style_header_sections
    chunk = subfile.get_next_chunk()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\MediaStation\Riff\SubFile.py", line 82, in get_next_chunk
    raise BinaryParsingError(
asset_extraction_framework.Exceptions.BinaryParsingError: Attempted to read a new chunk past the end of the subfile whose data starts at 0x18 and ends at 0x47e.

Position: 0x047e
Context:
0000045e  69 67 6f 64 18 00 00 00  03 00 0d 00 03 00 13 00  |igod............|
0000046e  03 00 a1 00 03 00 10 00  03 00 a1 00 03 00 00 00  |................|
0000047e  a1 00 10 00 00 00 6e 04  00 00 00 00 00 00        |......n.......|
0000048c

**Comment by npjg** [comment]
Yep, this was a bug. Guess I forgot to include this particular version of Pooh in my test data a few months ago. You can pull the latest from git if you want, or a new version will be published to PyPI eventually. (I have a few other enhancements to go in there.)
